export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_GRANDMAS = "GET_ALL_GRANDMAS";
export const GET_ALL_CUISINES = "GET_ALL_CUISINES";
export const FILTER_BY_CUISINES = "FILTER_BY_CUISINES";

export const GOT_ERROR = "GOT_ERROR";
